name: Manual Trigger Reformat

# configure manual trigger
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Reformat Python files
        if: steps.changed-python-files.outputs.any_changed == 'true'
        uses: psf/black@stable
        with:
          options: ""

      - name: Reformat JSON, YAML and MD files
        uses: creyD/prettier_action@v4.3
        with:
          dry: True
          file_pattern: "*.{json,yaml,md}"
          prettier_options: --check codes/**/*.json docs/*.md

